### ISSUE TITLE
Italy should be able to occupy Tunisia after France has fallen

### ISSUE THREAD

**Issue by StephenWasntAvailable** [StephenWasntAvailable/Fixing-The-Guns#15]
Description: This could be done via decision or event.

**Comment by Ydloh** [comment]
We need to revisit the Case Anton decision, which is currently not working IIRC. 
Case Anton could be available once the Allies set foot in North Africa or mainland France and makes Germany immediately declare war on Vichy.

**Comment by Ydloh** [comment]
Case Anton fixed and expanded. Tunisia will be transfered to germany, is italy is in Control of Lybia and the decision is taken.
