### ISSUE TITLE
Add the Invasion of Iran (Operation Countenance)

### ISSUE THREAD

**Issue by StephenWasntAvailable** [StephenWasntAvailable/Fixing-The-Guns#17]
Description:  Would have to have an actual gameplay purpose tho

**Comment by Ydloh** [comment]
Germany could get the chance to get in control of the anglo-iranian oil company through a historical operation or through facist rise in iran. This would make it strategically important to occupy those oil fields for the allies. Further more the iranian ports would already in  vanilla make good lend-lease ports for soviet russia. If facist support becomes too strong UK has a focus to declare war on iran IIRC

**Comment by SyrawMaximus** [comment]
This is supported since NSB in USSR focus tree.
