### ISSUE TITLE
Move Naval Techs to ealier dates. 

### ISSUE THREAD

**Issue by StephenWasntAvailable** [StephenWasntAvailable/Fixing-The-Guns#29]
Description: NO ONE has ever build a 1944 ship, a waste of 25% of the techs

Comments
"People have built 1944 subs, but yeah surface ships could do with a change
Would maybe need to nerf 44 subs if they can be acquired earlier -Stee"

**Comment by Ydloh** [comment]
One of the main problems could obviously be, that we barely reach 1944, not to speak of 1945. But switching everything one year earlier could be an option.

**Comment by StephenWasntAvailable** [comment]
I think a 1 year reduction could be a good starting point, probably also wouldn't really require any other balance changes
