### ISSUE TITLE
Germany should have fuel issues as the war goes on

### ISSUE THREAD

**Issue by StephenWasntAvailable** [StephenWasntAvailable/Fixing-The-Guns#34]

**Comment by Zittrich** [comment]
I would suggest either increasing fuel cosnumption of tanks or decreasing the fuel in romania

**Comment by SyrawMaximus** [comment]
Hello,

Maybe we can decrease Oil in Romania + give Germany resource rights to Iraq/Iran if they conquer the levant (just like how UK starts with resource rights in Iraq).

Regards,
Syraw.
