### ISSUE TITLE
Build in Faction Members Countries OR Decision / intel operation to establish port

### ISSUE THREAD

**Issue by StephenWasntAvailable** [StephenWasntAvailable/Fixing-The-Guns#36]
Might be difficult to implement

**Comment by Ydloh** [comment]
You could beforehand start an Operation, that will make a decision available, which creates a port. Possibly a failure could be implemented (failed Operation = no decision for port).

**Comment by StephenWasntAvailable** [comment]
Can build lots of things in ally territory now, closing
