### ISSUE TITLE
Battlefield Support Nerf / Other Doctrines Buff

### ISSUE THREAD

**Issue by StephenWasntAvailable** [StephenWasntAvailable/Fixing-The-Guns#37]

**Comment by StephenWasntAvailable** [comment]
To discuss: any changes we want to make to air doctrines?

**Comment by SyrawMaximus** [comment]
Hello,

Given the experience of the last few games, it seems that in Fighter vs Fighter wars, Battlefield Support is weak.
Given that people use CAS less and less these days, I think we should instead buff BS doctrine (maybe make those 2 exclusive doctrines not be exclusive?) or make division AA less deadly for CAS.

Regards,
Oussama.
