### ISSUE TITLE
Italy should be able to trigger Iraq to join the war(insurecction, civil war ecc) via decisions

### ISSUE THREAD

**Issue by StephenWasntAvailable** [StephenWasntAvailable/Fixing-The-Guns#9]
Description: (decisions that will add fascism support in Iraq. This can trigger also the already existant focus tree of the UK "Iraq Intervention". If the UK does no interveen, Iraq changes his politics in Fascism and join the Axis. Maybe let spawn some proper infrantry division just to cause distraction?)

**Comment by Ydloh** [comment]
You do not really need a decision to add fascism support in Iraq. For that you could just use your intelligence Service. Then the fascists nations could try to coup the government in Iraq with their intelligence service. Obviously Britain can either use their focus to intervene before a possible coup or they are forced to intervene in case the coup is succesfully.

I am not 100% sure, but I think what happened historically is already possible with the ingame mechanics.
